config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  resources :users do
    resources :questions
  end
  resources :questions do
    resources :answers
  end
  resources :sessions
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :questions
  belongs_to :users
  validates :response, :presence => true
  scope :todays_answers, -> { where("created_at >= ?", (DateTime.now - 1.days)).order(created_at: :desc)}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :users
  has_many :answers
  validates :question, :presence => true
  scope :newest_first, -> { order(created_at: :desc)}
  scope :todays_questions, -> { where("created_at >= ?", (DateTime.now - 1.days)).order(created_at: :desc)}

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_create :encrypt_password
  has_many :questions
  after_create :set_admin_status

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end


  def set_admin_status
    self.is_admin = false
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    if @answer.save
      flash[:notice] = "Your answer has been saved!"
      redirect_to question_path(@question)
    else
      render :new
    end
  end

private
  def answer_params
    params.require(:answer).permit(:response, :user_id, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't supposed to visit that page."
      redirect_to "/"
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize, only: [:new]

  def index
    @questions = Question.newest_first
    @todays_questions = Question.todays_questions.length
    @todays_answers = Answer.todays_answers.length
    @active_users = User.all
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new
  end

  def create
    @user = User.find(params[:user_id])
    @question = @user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Your question has been added!"
      redirect_to session_path(@user)
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
  end

private
  def question_params
    params.require(:question).permit(:question, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to session_path(@user)
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to new_session_path
    end
  end

  def show
    @current_user
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've succesfully signed up!"
      session[:user_id] = @user.id
      redirect_to session_path(@user)
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to new_user_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attribute(:is_admin, true)
      flash[:notice] = "User Admin Status Updated"
      redirect_to '/questions'
    else
      redirect_to '/'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User account has been deleted."
    redirect_to '/questions'
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render 'layouts/errors', :object => @answer %>

<%= form_for [@question, @answer] do |f| %>
  <div class="form-group">
    <%= f.label :response %>
    <%= f.text_area :response, class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/answers/new.html.erb
<h3><%= @question.question %></h3>

<h1 class="form-header">Add Answer</h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflowClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      <nav class="navbar">
       <div class="container-fluid">
        <div class="navbar-header">
          <br>
          <a href="/">Home</a>
        </div>
         <ul class="nav navbar-nav navbar-right">
          <li> <br> <%= current_user.email %> </li>
          <li>
            <%= link_to "Sign Out", session_path(current_user),
                :data => {:confirm => "Are you sure you want to sign out?",
                :method => "delete"} %>
          </li>
         </ul>
       </div>
     </nav>

    <% else %>
      <hr>
      <div class="container">
        <%= link_to "Sign up", new_user_path %> |
        <%= link_to "Sign in", new_session_path %>
      </div>
    <% end %>

    <div class="container">
      <% if flash[:notice] != nil %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] != nil %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', :object => @question %>

<%= form_for [current_user, @question] do |f| %>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_area :question, class: "form-control"%>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/questions/index.html.erb
<% if current_user %>

  <% if current_user.is_admin == true || current_user.email == 'admin'%>
    <div class="daily-stats">
      <div class="well">
        <p>Questions asked today: <%= @todays_questions %></p>
        <p>Answers given today: <%= @todays_answers %></p>
        <p>Total users: <%= @active_users.length %></p>
        <ul>
          <% @active_users.each do |user| %>
            <li> <%= link_to user.email, user_path(user) %> <br>  </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% else %>
    <h3>Questions Asked</h3>
    <%= link_to "Add a Question", new_user_question_path(current_user) %>
    <% if @questions.any? %>
      <ul>
        <% @questions.each do |question| %>
          <li><%= link_to question.question, question_path(question) %> | <%= question.answers.length %> </li>
        <% end %>
      </ul>
    <% else %>
      <p>No questions have been asked.</p>
    <% end %>
  <% end %>
<% else %>
  <h1>Welcome to the Stack Overflow Clone</h1>
<% end %>

app/views/questions/new.html.erb
<h1 class="form-header">Add Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h4><%= @question.question %> asked by <%= @user.email %></h4>
<hr>
<h5>Responses</h5>

<% if @question.answers.any? %>
<ul>
  <% @question.answers.each do |answer| %>
    <li><%= answer.response %></li>
  <% end %>
</ul>
<% else %>
  <p>No one has answered your question yet.</p>
<% end %>

<hr>
<p> <%= link_to "Add a response", new_question_answer_path(@question) %> </p>
<p><%= link_to "Back to All Questions", questions_path %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email, class: "form-control" %>
  <%= f.label "Password" %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>
<hr>

<%= form_for [@user] do |f| %>
  <div class="form-group">
    <%= f.label "Is Admin" %>
    <%= f.check_box :is_admin, class: "form-control"%>
  </div>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>


<p><%= link_to "Delete", user_path(@user),
            :data => {:confirm => "You sure?",
            :method => "delete"} %></p>